create database mnp;
use mnp;

select * from `3. sample sales data`;

rename table `3. sample sales data` to ssd;
#Display all sales records
select* from ssd;

# Show unique products sold
select distinct Product from ssd;

# Find the total number of sales transactions
select count(*) as Total_sales from ssd;

# Retrieve all sales made in the ‘West’ region
select * from ssd where Region = 'West';

# Get all records where the sales channel is ‘Online’
select * from ssd where Channel = 'Online';

#Find the total revenue generated by each region
select Region, sum(Revenue) as Total_Revenue from ssd
group by Region
order by  Total_Revenue desc;

# Calculate the total units sold per product
select Product, sum(Units_sold) as Total_units from ssd
group by Product
order by Total_units desc;

# Find the average revenue per sale for each salesperson
select Salesperson, avg(Revenue) as Avg_Revenue from ssd
group by Salesperson
order by Avg_Revenue desc;

# Display the top 5 highest revenue transactions
select * from ssd 
order by Revenue desc
limit 5;

# Count the number of transactions for each customer type
select Customer_Type, count(*) as Transaction_Count from ssd
group by Customer_Type;

# Find which region generated the highest total revenue
select Region, sum(Revenue) as Total_Revenue from ssd
group by Region
order by  Total_Revenue desc
limit 1;

# Identify the best-performing salesperson (highest total revenue)
select Salesperson, sum(Revenue) as Total_Revenue from ssd
group by Salesperson
order by Total_Revenue desc
limit 1;

# Determine which product has the highest average revenue per unit sold
select Product, avg(Revenue/ units_sold) as avg_Revenue_Per_unit from ssd
group by Product
order by avg_Revenue_Per_unit desc
limit 1;

# Compare total Online vs Offline sales revenue
select Channel, sum(Revenue) as Total_Revenue from ssd
group by Channel;

# Show monthly revenue trends for 2022
select MonthName(SalesDate) as Month, sum(Revenue) as Total_Revenue from ssd
group by Month
order by Month;

show columns from ssd;

ALTER TABLE ssd 
RENAME COLUMN `ï»¿Date` TO SalesDate;




